  name: Pull Request
  on:
    push:

  jobs:
    context:
      runs-on: ubuntu-latest
      steps:
        - name: go mod
          run: |
              go mod init
        - name: Run Terratest
          uses: cloudposse/github-action-terratest@main
          with:
            sourceDir: .
